added vidadeprogramador and vidadesuporte
tardypad/sailfishos-daily-comics pull request #86
Opened 2019-05-08 23:07 UTC by caio2k

Hello there,
Thanks for your great job creating this app. I've read the guideline to add a comic and I'm adding 2 local brazilian comics into your app but as I don't have yet the environment ready to compile I cannot test the build. Please evaluate if I need it tested before creating a PR.
Regards.

2019-05-12 17:43 UTC, tardypad commented
Thanks for the PR

A few comments besides the ones in the review:
- please also provide a 1000x1000 pixels cover.big.jpg just like the other ones have
- if you can, split the commit to have each comic added in its own.
Ideally they would be in 2 separate PR too to make it easier to review and merge.
- in the cover of "videdesuporte", display a single character without any object around it.

2019-05-15 13:14 UTC, caio2k commented
hey @tardypad i've updated the PR as you suggested. please take a look. whenever you accept it I will push the other PR with the next comics.

2019-05-15 15:17 UTC, tardypad requested changes

2019-05-15 15:17 UTC, tardypad commented on plugins/vidadeprogramador/extract.js
> +    var regex = /<img[^>]*src="([^"]*\/uploads\/[^"]*\/tirinha[^"]*.png)"/;
Unless there is a good reason for it, do not match the ".png" extension.
That way if the page change to use ".jpg" for example, the comic extraction wouldn't break.

2019-05-15 15:17 UTC, tardypad commented on plugins/vidadesuporte/extract.js
> +    var regex = /<img[^>]*src="([^"]*\/wp-content\/uploads\/[^"]*\/Suporte_[^"]*.jpg)"/;
Same as before, do not match the ".jpg" extension

2019-05-15 15:20 UTC, tardypad commented
Thanks for the changes, it looks fine now.
However there is one more small item to fix because I forgot to press submit to the review previously...
You can already open the other PR so I can look at them.

2019-05-16 13:12 UTC, caio2k commented on plugins/vidadeprogramador/extract.js
> +    var regex = /<img[^>]*src="([^"]*\/uploads\/[^"]*\/tirinha[^"]*.png)"/;
ok, done

2020-02-23 22:34 UTC, Olf0 commented
This is ready to be merged for 9 months, isn't it?

2020-02-23 22:44 UTC, caio2k commented
Yes, it is there for a while. I could not open a new PR because there is one file that cannot be forked properly...

2020-03-06 23:57 UTC, Maledictus approved these changes

2020-03-06 23:57 UTC, merged

2020-03-06 23:58 UTC, Maledictus commented
Thank you for your efforts